name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/docusaurus-builder:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Rust deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Node deps
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Clone Ewwii repo
        run: git clone --depth 1 https://github.com/Ewwii-sh/ewwii.git ewwii

      - name: Generate Rhai docs
        run: cargo run --release -p generate-rhai-docs
        working-directory: ./ewwii

      - name: Copy generated docs
        run: |
          mkdir -p ./docs/modules
          cp -r ./ewwii/tools/generate-rhai-docs/* ./docs/modules/

      - name: Build site
        run: pnpm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
