name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: curl -fsSL https://get.pnpm.io/install.sh | sh -

      - name: Cache Node deps
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Fix git ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build site
        run: pnpm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
