name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache system dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/apt-cache
          key: ${{ runner.os }}-debs-v1

      - name: Install APT dependencies
        run: |
          mkdir -p /tmp/apt-cache
          sudo apt-get update
          sudo apt-get -o dir::cache::archives="/tmp/apt-cache" install -y \
            pkg-config libcairo2-dev libglib2.0-dev libgirepository1.0-dev \
            libpango1.0-dev libatk1.0-dev libgtk-3-dev

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache Rust deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Clone Ewwii repo
        run: git clone --depth 1 https://github.com/Ewwii-sh/ewwii.git ewwii

      - name: Generate Rhai docs
        run: cargo run --release -p generate-rhai-docs
        working-directory: ./ewwii

      - name: Copy generated docs
        run: |
          mkdir -p ./docs/modules
          cp -r ./ewwii/tools/generate-rhai-docs/* ./docs/modules/

      - name: Build site
        run: pnpm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
