name: Build Builder Image

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - .github/docker/**
      - .github/workflows/docker.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: .github/docker/Dockerfile
          push: true
          tags: ghcr.io/ewwii-sh/docs/docusaurus-builder:latest
